services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tiagokelis2017@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - db
